lamguage: generic
sudo: required
services:
        - docker

before_install:
        - docker build -t testimage -f Dockerfile.dev .

script:
        - docker run -e CI=true Shik0/docker-react npm run test
