lamguage: generic
sudo: required
services:
        - docker

before_install:
        - docker build -t shahin/docker-react -f Dockerfile.dev .

script:
        - docker run -e CI=true shahin/docker-react npm run test
